### PR TITLE
Fix washed out images

### LINKED ISSUE #54: Some images are decoded washed out
Tested on `image` on commit 3b1fbcf2aedb809793a49d21ee5bb62ffafa3739 (the 0.25 branch), the testing methodology is same as in https://github.com/image-rs/image/issues/1872

Original:

dc-siamo-annuncio-breve-james-gunn-svela-progetti-presentati-v3-631174-1280x960 webp magick

Decoded by `image`:
dc-siamo-annuncio-breve-james-gunn-svela-progetti-presentati-v3-631174-1280x960 webp image

The same thing happens with small images. 

Original:

tr webp magick

Decoded by `image`:

tr webp image

Color doesn't seem to be necessary:

twitter webp magick

gets decoded as

twitter webp image

Github won't let me upload WebP images directly, so here are some diverging images as an archive: 
[image-webp-divergenes-3b1fbcf2ae-top.tar.gz](https://github.com/image-rs/image-webp/files/14325138/image-webp-divergenes-3b1fbcf2ae-top.tar.gz)

### PR DESCRIPTION
**Pull request by notjosh**
Fixes #54.

👋 Hiya! I was looking to use the library, but the (seemingly random) washed out images were a little worrying, so I found a fix: within `read_quantization_indices()`, `base` needed to be initialised with `yac_abs` when segments are not enabled.

With this change, the existing tests pass as well as the image from #49, and (most of the) images referred to in #54.

There are 3 images that cause test failures (currently commented out), but visually they appear almost identical. Below is a table of all the images from #54, with results from before and after this patch:

(I added diffs for the images that fail test to try and visualise the differences...but image diffing is hard, and I don't think the tool does a great job showing the diff?)

| Name | Passes Test | Reference | Before Fix | After Fix | Reference Diff |
| --- | --- | --- | --- | --- | --- |
| `26009_tf_eva_tarolo_teto_nelkul_13x9cm_by_dome_1_imgresize500x500` | ✅ | 26009_tf_eva_tarolo_teto_nelkul_13x9cm_by_dome_1_imgresize500x500 | 26009_tf_eva_tarolo_teto_nelkul_13x9cm_by_dome_1_imgresize500x500 | 26009_tf_eva_tarolo_teto_nelkul_13x9cm_by_dome_1_imgresize500x500 | - |
| `26010_tf_eva_tarolo_teto_nelkul_17x10cm_by_dome_1_imgresize500x500` | ✅ | 26010_tf_eva_tarolo_teto_nelkul_17x10cm_by_dome_1_imgresize500x500 | 26010_tf_eva_tarolo_teto_nelkul_17x10cm_by_dome_1_imgresize500x500 | 26010_tf_eva_tarolo_teto_nelkul_17x10cm_by_dome_1_imgresize500x500 | - |
| `circulaba_con_700_postes_de_madera_de_palo_santo_1` | ❌  | circulaba_con_700_postes_de_madera_de_palo_santo_1 | circulaba_con_700_postes_de_madera_de_palo_santo_1 | circulaba_con_700_postes_de_madera_de_palo_santo_1 | image |
| `community_groups` | ❌ | community_groups | community_groups | community_groups | image |
| `dc_siamo_annuncio_breve_james_gunn_svela_progetti_presentati_v3_631174_1280x960` | ❌ | dc_siamo_annuncio_breve_james_gunn_svela_progetti_presentati_v3_631174_1280x960 | dc_siamo_annuncio_breve_james_gunn_svela_progetti_presentati_v3_631174_1280x960 | dc_siamo_annuncio_breve_james_gunn_svela_progetti_presentati_v3_631174_1280x960 | image |
| `favicon_2023` | ✅ | favicon_2023 | favicon_2023 | favicon_2023 | - |
| `i48_22_8410_external` | ✅ | i48_22_8410_external | i48_22_8410_external | i48_22_8410_external | - |
| `menu_point` | ✅ | menu_point | menu_point | menu_point | - |
| `tr` | ✅ | tr | tr | tr | - |
| `twitter` | ✅ | twitter | twitter | twitter | - |

I'm fairly confident the differences are minor enough that we could ignore it (i.e. subtle YUV->RGB conversion differences), but there might actually be a deeper problem. In any case, this PR gets us much closer to correct, so at least it's a step forward regardless.

### CODE REVIEW

**Comment by fintelia** [comment]
Thanks for tracking down this issue! The code looks good to me and I agree that this is worth merging even though a few of the diverging images still don't completely match

The one concern I have is over the image licensing. The diverging images were obtained by scraping the internet and contain copyrighted contents. We can only include images that are freely licensed by their creator (or something like the 1x1 pixel regression.webp file that are too small for that to apply)

**Comment by notjosh** [comment]
> The one concern I have is over the image licensing

Ah, of course! I had thought about that, but then forgot about it as I got closer to midnight... 🤦 

I've rolled that commit back, and cherrypicked the commit from #49 to keep the committer history. Licensing should be okay now!

**Review by HeroicKatora — APPROVED** [review]
Agreed, code looks pretty nice. As I understand the diff, if `segment_values` were not enabled we'd get the `Default` for `delta_values` and this goes to a code path that also happens to ignore `yac_abc`. So even though the default for `quantizer_level` is unimportant, it'd fail to do the right thing.

Thanks for cleaning up the history.

The remaining differences might well be in the treatment of color spaces. Iirc most of the `image` libs try a little to hard to pretend like everything will be sRGB in the end and not all transforms taken due to that are always reasonable (and definitely not lossless). But that's just my best shot at a theory, if you intend to investigate further.

**Comment by fintelia** [comment]
To confirm, did you produce the reference PNGs by running dwebp with the -nofancy option?

The YUV to RGB conversion step of decoding lossy webp isn't precisely specified, but we attempt to get bit-exact output that matches that option. That's possible because our YUV conversion code is directly based on reading the implementation in libwebp.

The nice thing about getting bit exact output is that we can attribute all decoding differences to bugs in our implementation. Tests don't currently demand 100% of pixels to match because there's some bug that causes a small fraction of pixels to be slightly different over the test corpus. Hopefully we can track down the cause and get rid of the exception

**Comment by notjosh** [comment]
> To confirm, did you produce the reference PNGs by running dwebp with the -nofancy option?

Yup, in a batch. Specifically:

```
find /path/to/tests/images/divergenes -type f -iname "*.webp" -exec sh -c 'dwebp -nofancy {} -o /path/to/tests/reference/divergenes/$(basename {} .webp).png' \;
```

> The nice thing about targeting bit exact output is that we can attribute all decoding differences to bugs in our implementation.

That's a good point, makes sense.

**Comment by Shnatsel** [comment]
Perhaps we need our own `-nofancy` option, just like `libwebp`?

I recall the YUV to RGB conversion taking a significant percentage of the time in flame graphs. It would be great if we could optimize it further.

**Comment by fintelia** [comment]
We _only_ support the `-nofancy` formula. I'd be interested in figuring out what higher quality algorithm libwebp was using when the flag isn't passed and switching to that by default, but there isn't much documentation on what they do and I wasn't able to track it down in the libwebp source code.

**Pull request merged**
