### PR TITLE
Faster alpha blending

### PR DESCRIPTION
**Pull request by Shnatsel**
Switch to a direct translation of libwebp alpha blending, plus a tweak suggested by @awxkee in #119 to improve the precision of this approximation. 

It's not an exact match of the f64 method, but it is **more accurate than libwebp itself,** and without losing performance compared to the libwebp method (at least on my machine). The inaccuracies in both approximations show up only on very low alpha values, which makes them imperceptible.

This PR includes a test verifying this approximation against the floating-point reference.

libwebp is BSD licensed, which is not a viral license. This is also not the first instance of adapting code from libwebp based on the comments in the repo.

There's a case to be made for refactoring away the C-isms and also experimenting with `u16` instead of `u32` for intermediate values so that the outer loop could blend two pixels at once, but that would require much more work, and this is already a dramatic performance improvement on the sample from #119. Combined with https://github.com/image-rs/image-webp/pull/122 this reduces the end-to-end decoding time by 27%.

### CODE REVIEW

**Comment by Shnatsel** [comment]
Ah, test fail in big endian. Well, that's gonna be fun to debug. Thanks, C.

**Comment by Shnatsel** [comment]
I've fixed the endianness bug (good thing we have big-endian CI!), so this is now ready for review.

**Comment by Shnatsel** [comment]
Senpai has noticed my PR! :heart:

**Comment by fintelia** [comment]
I just realized that this PR updated some of the reference images without editing [CREDITS.md](https://github.com/image-rs/image-webp/blob/main/tests/CREDITS.md) which documents how they were generated. Specifically, they were previously produced by `dwebp` but now I think we're directly using decoded versions produced by this crate

**Comment by Shnatsel** [comment]
Oh, yes, that is correct. I did update the animated image sample because it differed very slightly.

**Pull request merged**
